### ISSUE TITLE
Set individual default padding for each side of modules in Global Settings

### ISSUE THREAD

**Issue by zackpyle** [beaverbuilder/feature-requests#182] opened 2021-08-23 20:15 UTC
**Is your feature request related to a problem? Please describe.**
I don't like bottom padding on modules

**Describe the solution you'd like**
In Global Styles, there is a section to set the default padding for modules, but there is only one input so they are all the same. I would like this to be separated out into top, right, bottom, left

![Screen Shot 2021-08-23 at 15 13 28](https://user-images.githubusercontent.com/19413506/130513341-be2b5d62-33e9-431a-bc99-80c967b99868.jpg)

**Comment by codente** [comment] 2021-08-23 20:19
Duplicate of #132

**Comment by codente** [comment] 2022-09-13 16:26
In 2.6!

**Closed by codente** 2022-09-13 16:26 UTC
Labels: Beaver Builder, Done + Testing
