### ISSUE TITLE
Fixed Header Fade-in in Themer just like in the BB Theme

### ISSUE THREAD

**Issue by jaycollier** [beaverbuilder/feature-requests#302] opened 2023-01-20 21:21 UTC
The Beaver Builder Theme has a Fixed Header with a Fade-In.

Beaver Themer Header layout does not.

Please add it to the Themer.

**Comment by A-Buzon** [comment] 2023-02-07 15:50
This is a duplicate of #170
@jaycollier be sure to go **give that one a thumbs up!**  It was requested way back in July 2021 and obviously never acted on.

**Comment by jaycollier** [comment] 2023-02-07 20:56
Thank you! Will do.On Feb 7, 2023, at 10:50 AM, Abby Buzon ***@***.***> wrote:﻿
This is a duplicate of #170
@jaycollier be sure to go give that one a thumbs up!  It was requested way back in July 2021 and obviously never acted on.

**Closed** 2023-02-15 14:19 UTC
Labels: Beaver Themer
