### ISSUE TITLE
Add page structure view. 

### ISSUE THREAD

**Issue by iamandrewpeters** [beaverbuilder/feature-requests#27] opened 2020-07-28 19:57 UTC
**Is your feature request related to a problem? Please describe.**
The longer pages get the harder it is to get a birds eye view of the structure of the page. 

**Describe the solution you'd like**
Window or modal to view the pages overall layout and structure. Ability to name rows/columns to organize better. 

**Describe alternatives you've considered**

**Additional context**

**Comment by codente** [comment] 2020-07-28 20:08
Duplicate of #1

**Closed by codente** 2020-07-28 20:08 UTC
Labels: Beaver Builder
