### ISSUE TITLE
Add more button styles to the customiser

### ISSUE THREAD

**Issue by codepuncher** [beaverbuilder/feature-requests#169] opened 2021-07-12 16:09 UTC
**Is your feature request related to a problem? Please describe.**
Most designs/sites have more than one style/type of button. Bootstrap itself has multiple button styles. It's quite frustrating that the BB theme has only 1 that can be styled.

**Describe the solution you'd like**
A set of buttons (maybe repeatable?) in the customiser that you can customise.

**Describe alternatives you've considered**
Whilst we can add in our own customiser fields, they are custom and not a part of the original/parent theme. This needs to be integrated into the main BB theme and not child theme.

**Additional context**

**Comment by codente** [comment] 2021-07-12 16:15
Duplicate of #133

**Closed by codente** 2021-07-12 16:15 UTC
Labels: BB Theme
