### ISSUE TITLE
Motion Effects 

### ISSUE THREAD

**Issue by thesoftworker** [beaverbuilder/feature-requests#391] opened 2024-12-05 09:20 UTC
It would be nice that Motion Effects will be directly available from the Beaver Builder page builder.
Elementor has this readily available on any of its widgets/modules - https://elementor.com/features/motion-effects/

When I contacted Beaver Builder for this, I am suggested with https://motion.page/

**Comment by codente** [comment] 2024-12-05 13:13
Duplicate of #28

**Closed as completed by codente** 2024-12-05 13:13 UTC
Labels: Beaver Builder
