### ISSUE TITLE
Preserve syntax highlighting in Dark Mode

### ISSUE THREAD

**Issue by gingersoulrecords** [beaverbuilder/feature-requests#90] opened 2020-12-11 22:13 UTC
When you're in Dark Mode, there's a line of !important CSS (line 252 in bb-plugin/css/fl-builder-ui-skin-dark.css) that brute-forces all elements (except `<i>` elements) to have a light gray color. 

```
.fl-builder-ui-skin--dark .fl-lightbox *:not(i) {
    color: #a7b1bb !important;
}

```
This effectively nullifies syntax highlighting, making it difficult to manage custom HTML/CSS/JS, whether you're working with an HTML module or Global/Layout CSS/JS. The module API allows for a code (Ace) editor, which is also rendered in grayscale with this CSS.

Beaver Builder is for non-coders, sure, but these in-builder editors are vital for fine-tuning professional sites built on the framework, and this bug forces devs to 'work without syntax highlighting' if they want to use Dark Mode. 

The solution involves removing this line of code and 'doing the work' of coloring specific elements deliberately for dark mode (there aren't many). Using the universal (*) selector combined with !important closes a lot of styling doors, both on the native elements and (cough) 3rd party developer work.

Full disclosure - I'd like to use CodeMirror (and all of its extensions, like Emmet) via a custom module, but I also use custom CSS all the time and would like to do some tutorials with Dark Mode on

![image](https://user-images.githubusercontent.com/8520042/101959851-2aacb800-3bd4-11eb-8c67-85a7ff8c5c63.png)

Thanks for reading!

DB

**Comment by codente** [comment] 2020-12-11 22:39
Duplicate of #88

**Closed by codente** 2020-12-11 22:39 UTC
Labels: Beaver Builder

**Comment by Dannyholt** [comment] 2020-12-14 19:21
@gingersoulrecords 

This and #88 were closed because we consider this a bug not a feature request. ;)
