### ISSUE TITLE
Vertical and Horizontal scroll animations

### ISSUE THREAD

**Issue by Dzinr4001** [beaverbuilder/feature-requests#352] opened 2024-01-04 14:39 UTC
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
I recently saw a Wix ad for their new features which are vertical and horizontal scroll animations. This feature is where a user scrolls down the page or to the left/right and as they are scrolling, graphic elements are moving across the screen. The feature is seen a lot on Apple's website for their mac computers and iphones. 

**Describe alternatives you've considered**
The closest feature on BB is parallax which I've used before but it's not the same. 

**Additional context**
Here is a reference to the scoll animation I saw. The information is on Wix's website
https://support.wix.com/en/article/wix-editor-using-animation-and-scroll-effects-on-your-mobile-site

**Comment by codente** [comment] 2024-01-04 14:43
Seems like a duplicate of #28

**Closed by codente** 2024-01-04 14:43 UTC
Labels: Beaver Builder
