### ISSUE TITLE
Motion Controls

### ISSUE THREAD

**Issue by pixelloop** [beaverbuilder/feature-requests#101] opened 2021-01-27 00:29 UTC
This relates to a new feature.

One reason I am having to use Elementor more is due to the lack of motion effects and the way animations are handled.

https://elementor.com/blog/introducing-motion-effects/ 

I think this would make beaver builder more interesting for designers and help it to keep pace with the other options out there including webflow. 

BeaverBuilder offers the best overall user experience but it hasn't evolved much in the features for designers for some time.

**Comment by codente** [comment] 2021-01-27 14:48
Please do a search before making a feature request.  Duplicate of #28

**Closed by codente** 2021-01-27 14:48 UTC
Labels: Beaver Builder
