### ISSUE TITLE
Absolute Option Like Elementor

### ISSUE THREAD

**Issue by CypressWebs** [beaverbuilder/feature-requests#305] opened 2023-02-11 21:18 UTC
I tried out Elementor and they have the option to have an image or colored background be used as Absolute and can move it around the page as needed. It's a great feature to put images over the page or around the text.

Here is a link to their feature: https://elementor.com/help/how-to-set-absolute-position-for-an-element/

**Comment by codente** [comment] 2023-02-11 21:47
Duplicate of #251

**Closed by codente** 2023-02-11 21:47 UTC
Labels: Beaver Builder
