### ISSUE TITLE
Make row and column settings responsive

### ISSUE THREAD

**Issue by dmvdev01** [beaverbuilder/feature-requests#322] opened 2023-04-19 15:43 UTC
Please make these settings responsive.

<img src="https://i2.paste.pics/f25b1936ef17f6e62c00bf3495e59c2f.png" width="878" height="692" alt="Screenshot">

<img src="https://i2.paste.pics/ab72d090b4d559ba30fbedc051fc68a6.png" width="1010" height="664" alt="Screenshot">

**Comment by codente** [comment] 2023-04-19 15:48
Duplicate of #299.  You can add your request there for columns.

**Closed by codente** 2023-04-19 15:48 UTC
Labels: Beaver Builder
