### ISSUE TITLE
Global Colors

### ISSUE THREAD

**Issue by tiniiiii** [beaverbuilder/feature-requests#319] opened 2023-04-11 15:40 UTC
If I want to change a client's brand color or (parts of) its color palette I need to manually update the colors of a lot of elements that have a/this particular color assigned. If a website contains multiple pages and various customized elements this gets very time-consuming. Also, it's easily possible to miss some colors.

It would be awesome if it was possible to make changes in the e.g. color preset - which automatically affect all color occurrences on the website. 

Alternatively, it would be nice if it's possible to add custom properties to the color picker (additionally to the e.g. hex code or RGBA code). 
https://developer.mozilla.org/en-US/docs/Web/CSS/--*

Thanks! :)

**Comment by codente** [comment] 2023-04-11 15:43
Duplicate of #6.

**Closed by codente** 2023-04-11 15:43 UTC
Labels: Beaver Builder
