### ISSUE TITLE
Better UI - Show row, column and module names inside action blocks on hover

### ISSUE THREAD

**Issue by Bobolinos** [beaverbuilder/feature-requests#115] opened 2021-03-04 08:51 UTC
**Is your feature request related to a problem? Please describe.**
BB users often don't understand the differences in a row/column/module in the current UI. It would help to name those.

**A clear and concise description of what you want to happen.**
Show name of column/row or module name inside action blocks on hover. Show the word "Column" on empty column.

**Describe the solution you'd like**
The idea is to add the name "Row", "Column" or the name of the module like "Heading" to the BB block overlay actions when you hover over it. This way the user understands better where to click. A user understands that a column is inside a row, but often is confused what is the row. If you have a full width row with an empty column inside, the user does not understand what the row is.
![Screenshot 2021-03-04 at 09 30 25](https://user-images.githubusercontent.com/57323118/109937365-1eb22d00-7ccf-11eb-8bcd-4bddace7e93f.png)

**Comment by codente** [comment] 2021-03-04 13:57
Duplicate of #8

**Closed by codente** 2021-03-04 13:57 UTC
Labels: Beaver Builder
