### ISSUE TITLE
Append & Prepend modules.

### ISSUE THREAD

**Issue by zenics** [beaverbuilder/feature-requests#45] opened 2020-08-11 16:18 UTC
**Is your feature request related to a problem? Please describe.**
I am sure everyone here dealt with this before. When you have let's say a post-module, you add a heading module at the top for that, now you can set the post-module to show/hide when there are no posts but you can hide the heading module with it. 

**Describe the solution you'd like**
It would be great to have a function to append/prepend a saved module that acts all together with the module you use. 

**Describe alternatives you've considered**
I have created this module extension which is basically a js solution for post modules to hide any node if post module(s) empty. [https://github.com/zenics/bb-hidethis](https://github.com/zenics/bb-hidethis). With this, you can check if the post-module empty and if it is you can hide any module on the page. this is what I use currently to hide post module 's headings.

**Additional context**

**Comment by codente** [comment] 2020-08-20 02:05
Is this similar to or the same as #4 ?

**Comment by codente** [comment] 2021-12-11 20:23
Duplicate of #4

**Closed by codente** 2021-12-11 20:23 UTC
Labels: Beaver Builder
