### ISSUE TITLE
Ability to see where "global" rows/modules/columns, etc, are being used

### ISSUE THREAD

**Issue by ksousa** [beaverbuilder/feature-requests#256] opened 2022-06-29 08:07 UTC
I love the ability to save a a row/module/column as a global element. It would be really useful, however, if you you could know where these elements are being used in the event you need to delete them/check how it looks after updating them.

**Comment by codente** [comment] 2022-10-09 18:34
Duplicate of #191

**Closed by codente** 2022-10-09 18:34 UTC
Labels: Beaver Builder
